In [1]:
import os

In [2]:
os.listdir()

['.ipynb_checkpoints',
 'climate.txt',
 'data',
 'italy_covid_daywise.csv',
 'jupyter 1 ,basic python.ipynb',
 'jupyter 2 , start with numpy.ipynb',
 'location.csv',
 'new_file',
 'new_folder',
 'python 3 , starting with pandas (tabular data).ipynb']

In [3]:
import urllib.request

In [4]:
italy_covid_daywise = "https://raw.githubusercontent.com/aditya08xyz/practise-csv-file/refs/heads/main/italy-covid-daywise.csv"

In [5]:
urllib.request.urlretrieve(italy_covid_daywise, 'italy_covid_daywise.csv')    #now u will a new directory has been formed by the name of italy covid daywise.csv

('italy_covid_daywise.csv', <http.client.HTTPMessage at 0x298f1139950>)

In [6]:
os.listdir()

['.ipynb_checkpoints',
 'climate.txt',
 'data',
 'italy_covid_daywise.csv',
 'jupyter 1 ,basic python.ipynb',
 'jupyter 2 , start with numpy.ipynb',
 'location.csv',
 'new_file',
 'new_folder',
 'python 3 , starting with pandas (tabular data).ipynb']

In [7]:
!pip install pandas
import pandas as pd

[notice] A new release of pip is available: 25.1.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\poona\appdata\local\programs\python\python313\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\poona\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\poona\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\poona\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\poona\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
covid_df = pd.read_csv('italy_covid_daywise.csv')  # suffix _df represent pandas dataframe    , there can be pd.read_excel/json/....etc

In [9]:
type(covid_df)

pandas.DataFrame

In [10]:
covid_df      #NaN MEANS data not given there

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [11]:
covid_df.info()     # u can see there are less non null count in new_tests (135) as in csv file some data were not given on new_tests
# try to analise the output in detail
# count generally means no. of data (in this case, no. of cases with available data)

<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    str
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), str(1)
memory usage: 7.9 KB

In [12]:
covid_df.describe()   #mean = average so from the output u can see the avg no of everyday cases were 1094, & std > mean  i.e by time the new cases increases by days :( , and there was a day with max no. of cases with 6557 cases

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

In [13]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

In [14]:
covid_df.shape

(248, 4)

# in numpy one , we did list of dictionaries , HERE  we will be doing dictionary of lists

In [15]:
# pandas is most familiar with dict of lists
covid_data_dict = {
     'date': ['2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-02'],
     'new_cases': [1444, 1365, 996, 975, 1326],
     'new_dates': [1, 4, 6, 8, 6],
     'new_tests': [53541, 42583, 54395, None, None]
}

In [16]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [17]:
covid_data_dict['new_cases']

[1444, 1365, 996, 975, 1326]

In [18]:
covid_df['new_cases']    # now u can see how pandas uses indexing , use brain

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

In [19]:
type(covid_df['new_cases'])   #so the above data we get using pandas indexing is actually a series

pandas.Series

In [20]:
covid_df['new_cases'][246]    # pandas series is used to easily axcess the indexing

np.float64(975.0)

In [21]:
covid_df['new_tests'][243]

np.float64(53541.0)

In [22]:
# .at method (useful)
covid_df.at[246, 'new_cases']     # useful

np.float64(975.0)

In [23]:
# instead of using indexing notation [] , pandas allows dot . 
covid_df.new_cases    #same as covid_df['new_cases]

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

In [24]:
# now to access multiple column or u say the subset of the dataframe 
cases_df = covid_df[['date','new_cases']]  #inside indexing notation we are passing a full list of columns
cases_df                           # remember the memory is only one , so if u change value in covid_df then it automatically changes the other dataframes values derieved by it,

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
243  2020-08-30     1444.0
244  2020-08-31     1365.0
245  2020-09-01      996.0
246  2020-09-02      975.0
247  2020-09-03     1326.0

[248 rows x 2 columns]

In [25]:
# but if u dont want the change in all then u can use copy method and create a seperate dataframe
covid_df_copy = covid_df.copy
covid_df_copy

<bound method NDFrame.copy of            date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]>

In [26]:
covid_df   #NaN stands for not a number , but its type is float , u can check it using type(covid_df.at[0, 'new_tests'])

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [27]:
covid_df.loc[243]

date          2020-08-30
new_cases         1444.0
new_deaths           1.0
new_tests        53541.0
Name: 243, dtype: object

In [28]:
covid_df.head(5)   #to get the first 5 rows

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [29]:
covid_df.tail(4)   #last 4 rows

           date  new_cases  new_deaths  new_tests
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

In [30]:
# u can see the new tests has nan values for many starting indexes, to check its first value 
covid_df.new_tests.first_valid_index()

111

In [31]:
# now to verify the above result
covid_df.loc[108:113]

           date  new_cases  new_deaths  new_tests
108  2020-04-17     3786.0       525.0        NaN
109  2020-04-18     3493.0       575.0        NaN
110  2020-04-19     3491.0       480.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0

In [32]:
covid_df.sample(10)     # it will give 10 random rows

           date  new_cases  new_deaths  new_tests
74   2020-03-14     2547.0       252.0        NaN
104  2020-04-13     4092.0       431.0        NaN
228  2020-08-15      574.0         3.0    25937.0
79   2020-03-19     4207.0       473.0        NaN
57   2020-02-26       93.0         5.0        NaN
162  2020-06-10      283.0        79.0    37865.0
195  2020-07-13      234.0         9.0    14006.0
219  2020-08-06      384.0        10.0    32169.0
167  2020-06-15      338.0        44.0    17463.0
95   2020-04-04     4585.0       764.0        NaN

In [33]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()

In [34]:
death_rate = covid_df.new_deaths.sum() / covid_df.new_cases.sum()

In [35]:
print("the overal reported death rate in italy is reported as {:.2f}% ".format(death_rate*100))    #:.2f for 2 decimal float value

the overal reported death rate in italy is reported as 13.07%

In [36]:
# as u can see the total new_test value is not given (written NaN) SO let the 935310 tests were conducted before the data written
initial_tests = 935310
total_tests = initial_tests + covid_df.new_tests.sum()
total_tests

np.float64(5214766.0)

In [37]:
positive_rate = total_cases / total_tests

In [38]:
print("{:.2f} % of tests in italy led to a positive diagnosis".format(positive_rate * 100))

5.21 % of tests in italy led to a positive diagnosis

In [39]:
high_new_cases = covid_df.new_cases > 1000        # we get the series of boolean as an output
high_new_cases

0      False
1      False
2      False
3      False
4      False
       ...
243     True
244     True
245    False
246    False
247     True
Name: new_cases, Length: 248, dtype: bool

In [40]:
covid_df[high_new_cases]    # subset of original dataframe covid_df  , basically it is also a dataframe , also u can see there are 72 days with no of new cases were higher than 1000
# can also written as covid_df[covid_df.new_cases > 1000 ] directly
# basically remember [big bracket] is use for indexing , ie getting the value.

           date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
..          ...        ...         ...        ...
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

[72 rows x 4 columns]

u can see the pandas usually hides the much part of rows to fit in display but if we want all the rows

In [41]:
from IPython.display import display
with pd.option_context('display.max_rows',100):      #it takes alot of memory and space
    display(covid_df[covid_df.new_cases > 1000])

           date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
74   2020-03-14     2547.0       252.0        NaN
75   2020-03-15     3497.0       173.0        NaN
76   2020-03-16     2823.0       370.0        NaN
77   2020-03-17     4000.0       347.0        NaN
78   2020-03-18     3526.0       347.0        NaN
79   2020-03-19     4207.0       473.0        NaN
80   2020-03-20     5322.0       429.0        NaN
81   2020-03-21     5986.0       625.0        NaN
82   2020-03-22     6557.0       795.0        NaN
83   2020-03-23     5560.0       649.0        NaN
84   2020-03-24     4789.0       601.0        NaN
85   2020-03-25     5249.0       743.0        NaN
86   2020-03-26     5210.0       685.0        NaN
87   2020-03-27     6153.0       660.0        NaN
88   2020-03-28     5959.0       971.0        NaN
89   2020-03-29     5974.0       887.0        NaN
90   2020-03-30     5217.0       758.0        NaN
91   2020-03-31     4050.0       810.0        NaN
92   2020-04-01     4053.0       839.0        NaN
93   2020-04-02     4782.0       727.0        NaN
94   2020-04-03     4668.0       760.0        NaN
95   2020-04-04     4585.0       764.0        NaN
96   2020-04-05     4805.0       681.0        NaN
97   2020-04-06     4316.0       527.0        NaN
98   2020-04-07     3599.0       636.0        NaN
99   2020-04-08     3039.0       604.0        NaN
100  2020-04-09     3836.0       540.0        NaN
101  2020-04-10     4204.0       612.0        NaN
102  2020-04-11     3951.0       570.0        NaN
103  2020-04-12     4694.0       619.0        NaN
104  2020-04-13     4092.0       431.0        NaN
105  2020-04-14     3153.0       564.0        NaN
106  2020-04-15     2972.0       604.0        NaN
107  2020-04-16     2667.0       578.0        NaN
108  2020-04-17     3786.0       525.0        NaN
109  2020-04-18     3493.0       575.0        NaN
110  2020-04-19     3491.0       480.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
115  2020-04-24     2646.0       464.0    95273.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0
118  2020-04-27     2324.0       260.0    26678.0
119  2020-04-28     1739.0       333.0    37554.0
120  2020-04-29     2091.0       382.0    38589.0
121  2020-04-30     2086.0       323.0    41441.0
122  2020-05-01     1872.0       285.0    43732.0
123  2020-05-02     1965.0       269.0    31231.0
124  2020-05-03     1900.0       474.0    27047.0
125  2020-05-04     1389.0       174.0    22999.0
126  2020-05-05     1221.0       195.0    32211.0
127  2020-05-06     1075.0       236.0    37771.0
128  2020-05-07     1444.0       369.0    13665.0
129  2020-05-08     1401.0       274.0    45428.0
130  2020-05-09     1327.0       243.0    36091.0
131  2020-05-10     1083.0       194.0    31384.0
134  2020-05-13     1402.0       172.0    37049.0
236  2020-08-23     1071.0         3.0    47463.0
237  2020-08-24     1209.0         7.0    33358.0
240  2020-08-27     1366.0        13.0    57640.0
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

In [42]:
# note : 
"""
method 1:
import urllib.request
urllib.request.urlretrieve('url1', './data/loan1.csv')

method 2 :
from urllib.request import urlretrieve
urlretrieve('url1' , './data/loan1.csv')
"""

"\nmethod 1:\nimport urllib.request\nurllib.request.urlretrieve('url1', './data/loan1.csv')\n\nmethod 2 :\nfrom urllib.request import urlretrieve\nurlretrieve('url1' , './data/loan1.csv')\n"

In [43]:
high_ratio_df = covid_df[ covid_df.new_cases / covid_df.new_tests > positive_rate]    # it will do the element wide division and then check if the value is greater than the average or not
high_ratio_df   # output days are the days in which more people got infected than the avg trend

           date  new_cases  new_deaths  new_tests
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0
118  2020-04-27     2324.0       260.0    26678.0
120  2020-04-29     2091.0       382.0    38589.0
123  2020-05-02     1965.0       269.0    31231.0
124  2020-05-03     1900.0       474.0    27047.0
125  2020-05-04     1389.0       174.0    22999.0
128  2020-05-07     1444.0       369.0    13665.0

In [44]:
covid_df["positive_rate"]= (covid_df.new_cases / covid_df.new_tests)*100
covid_df

           date  new_cases  new_deaths  new_tests  positive_rate
0    2019-12-31        0.0         0.0        NaN            NaN
1    2020-01-01        0.0         0.0        NaN            NaN
2    2020-01-02        0.0         0.0        NaN            NaN
3    2020-01-03        0.0         0.0        NaN            NaN
4    2020-01-04        0.0         0.0        NaN            NaN
..          ...        ...         ...        ...            ...
243  2020-08-30     1444.0         1.0    53541.0       2.696999
244  2020-08-31     1365.0         4.0    42583.0       3.205505
245  2020-09-01      996.0         6.0    54395.0       1.831051
246  2020-09-02      975.0         8.0        NaN            NaN
247  2020-09-03     1326.0         6.0        NaN            NaN

[248 rows x 5 columns]

but in this data there would cases where tests conducted today while the new cases of being positive arrive after 2-3 days after so we cant really do the element wise division to get the positive rate , so always remember to check and analyise the given data based on own thinking and always check for more and more information abt the data

In [45]:
#so lets remove the positive rate column cuz of it doesnt provide the accurate +ve rate
covid_df.drop(columns=["positive_rate"], inplace=True)       #inplace true means to change that column from original dataframe instead of creating a copy
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

sorting the dataframe

In [46]:
covid_df.sort_values('new_cases', ascending= False).head(5)   # note theres not a descending , so ascending false means descending , head is used to get the top 5 results

          date  new_cases  new_deaths  new_tests
82  2020-03-22     6557.0       795.0        NaN
87  2020-03-27     6153.0       660.0        NaN
81  2020-03-21     5986.0       625.0        NaN
89  2020-03-29     5974.0       887.0        NaN
88  2020-03-28     5959.0       971.0        NaN

In [47]:
covid_df.sort_values('new_deaths', ascending= False).head(5)   # rip 28th march   # and remember by default it takes the ascending order by default

          date  new_cases  new_deaths  new_tests
88  2020-03-28     5959.0       971.0        NaN
89  2020-03-29     5974.0       887.0        NaN
92  2020-04-01     4053.0       839.0        NaN
91  2020-03-31     4050.0       810.0        NaN
82  2020-03-22     6557.0       795.0        NaN

In [48]:
# also we ve taken a real world data , so errors are the part of real wrorld data, eg-
covid_df.sort_values('new_cases').head(5)

           date  new_cases  new_deaths  new_tests
172  2020-06-20     -148.0        47.0    29875.0
0    2019-12-31        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN

In [49]:
covid_df[169:174]   # u can see the error in data entry , not our fault :)

           date  new_cases  new_deaths  new_tests
169  2020-06-17      210.0        34.0    33957.0
170  2020-06-18      328.0        43.0    32921.0
171  2020-06-19      331.0        66.0    28570.0
172  2020-06-20     -148.0        47.0    29875.0
173  2020-06-21      264.0        49.0    24581.0

In [50]:
# now lets modify that entry , so we put there by taking the avg of new_cases value or simply the avg of previous and next day cases which makes more sense here
covid_df.at[172, 'new_cases'] = covid_df.at[171,'new_cases'] + covid_df.at[173,'new_cases'] / 2        # .at is used to go for specific value 
covid_df[171:174]

           date  new_cases  new_deaths  new_tests
171  2020-06-19      331.0        66.0    28570.0
172  2020-06-20      463.0        47.0    29875.0
173  2020-06-21      264.0        49.0    24581.0

In [51]:
covid_df.date

0      2019-12-31
1      2020-01-01
2      2020-01-02
3      2020-01-03
4      2020-01-04
          ...
243    2020-08-30
244    2020-08-31
245    2020-09-01
246    2020-09-02
247    2020-09-03
Name: date, Length: 248, dtype: str

In [52]:
covid_df['date'] = pd.to_datetime(covid_df.date)         #to change the datatype to datetime so that in next cell to perform datetimeIndex function 
covid_df.date

0     2019-12-31
1     2020-01-01
2     2020-01-02
3     2020-01-03
4     2020-01-04
         ...
243   2020-08-30
244   2020-08-31
245   2020-09-01
246   2020-09-02
247   2020-09-03
Name: date, Length: 248, dtype: datetime64[us]

In [53]:
# now 
covid_df['years']= pd.DatetimeIndex(covid_df.date).year
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday        # 0=monday to 6=sunday

In [54]:
covid_df

          date  new_cases  new_deaths  new_tests  years  month  day  weekday
0   2019-12-31        0.0         0.0        NaN   2019     12   31        1
1   2020-01-01        0.0         0.0        NaN   2020      1    1        2
2   2020-01-02        0.0         0.0        NaN   2020      1    2        3
3   2020-01-03        0.0         0.0        NaN   2020      1    3        4
4   2020-01-04        0.0         0.0        NaN   2020      1    4        5
..         ...        ...         ...        ...    ...    ...  ...      ...
243 2020-08-30     1444.0         1.0    53541.0   2020      8   30        6
244 2020-08-31     1365.0         4.0    42583.0   2020      8   31        0
245 2020-09-01      996.0         6.0    54395.0   2020      9    1        1
246 2020-09-02      975.0         8.0        NaN   2020      9    2        2
247 2020-09-03     1326.0         6.0        NaN   2020      9    3        3

[248 rows x 8 columns]

In [55]:
# now to work on specific portion of data ( cuz the above date is so big) , so lets take a month data and analyze
covid_df_may=covid_df[covid_df.month==5]
covid_df_may

          date  new_cases  new_deaths  new_tests  years  month  day  weekday
122 2020-05-01     1872.0       285.0    43732.0   2020      5    1        4
123 2020-05-02     1965.0       269.0    31231.0   2020      5    2        5
124 2020-05-03     1900.0       474.0    27047.0   2020      5    3        6
125 2020-05-04     1389.0       174.0    22999.0   2020      5    4        0
126 2020-05-05     1221.0       195.0    32211.0   2020      5    5        1
127 2020-05-06     1075.0       236.0    37771.0   2020      5    6        2
128 2020-05-07     1444.0       369.0    13665.0   2020      5    7        3
129 2020-05-08     1401.0       274.0    45428.0   2020      5    8        4
130 2020-05-09     1327.0       243.0    36091.0   2020      5    9        5
131 2020-05-10     1083.0       194.0    31384.0   2020      5   10        6
132 2020-05-11      802.0       165.0    25823.0   2020      5   11        0
133 2020-05-12      744.0       179.0    39620.0   2020      5   12        1
134 2020-05-13     1402.0       172.0    37049.0   2020      5   13        2
135 2020-05-14      888.0       195.0    41131.0   2020      5   14        3
136 2020-05-15      992.0       262.0    39027.0   2020      5   15        4
137 2020-05-16      789.0       242.0    40657.0   2020      5   16        5
138 2020-05-17      875.0       153.0    33505.0   2020      5   17        6
139 2020-05-18      675.0       145.0    26101.0   2020      5   18        0
140 2020-05-19      451.0        99.0    40226.0   2020      5   19        1
141 2020-05-20      813.0       162.0    38617.0   2020      5   20        2
142 2020-05-21      665.0       161.0    40644.0   2020      5   21        3
143 2020-05-22      642.0       156.0    42987.0   2020      5   22        4
144 2020-05-23      652.0       130.0    42579.0   2020      5   23        5
145 2020-05-24      669.0       119.0    34206.0   2020      5   24        6
146 2020-05-25      531.0        50.0    20676.0   2020      5   25        0
147 2020-05-26      300.0        92.0    33944.0   2020      5   26        1
148 2020-05-27      397.0        78.0    37299.0   2020      5   27        2
149 2020-05-28      584.0       117.0    39838.0   2020      5   28        3
150 2020-05-29      593.0        70.0    38233.0   2020      5   29        4
151 2020-05-30      516.0        87.0    36051.0   2020      5   30        5
152 2020-05-31      416.0       111.0    28948.0   2020      5   31        6

In [56]:
covid_df_may_metrices = covid_df_may[['new_cases','new_deaths','new_tests']]      # [[ ]] is to define which column to keep only
covid_df_may_metrices

     new_cases  new_deaths  new_tests
122     1872.0       285.0    43732.0
123     1965.0       269.0    31231.0
124     1900.0       474.0    27047.0
125     1389.0       174.0    22999.0
126     1221.0       195.0    32211.0
127     1075.0       236.0    37771.0
128     1444.0       369.0    13665.0
129     1401.0       274.0    45428.0
130     1327.0       243.0    36091.0
131     1083.0       194.0    31384.0
132      802.0       165.0    25823.0
133      744.0       179.0    39620.0
134     1402.0       172.0    37049.0
135      888.0       195.0    41131.0
136      992.0       262.0    39027.0
137      789.0       242.0    40657.0
138      875.0       153.0    33505.0
139      675.0       145.0    26101.0
140      451.0        99.0    40226.0
141      813.0       162.0    38617.0
142      665.0       161.0    40644.0
143      642.0       156.0    42987.0
144      652.0       130.0    42579.0
145      669.0       119.0    34206.0
146      531.0        50.0    20676.0
147      300.0        92.0    33944.0
148      397.0        78.0    37299.0
149      584.0       117.0    39838.0
150      593.0        70.0    38233.0
151      516.0        87.0    36051.0
152      416.0       111.0    28948.0

In [57]:
covid_may_total = covid_df_may_metrices.sum()
covid_may_total

new_cases       29073.0
new_deaths       5658.0
new_tests     1078720.0
dtype: float64

In [58]:
#can even do the above in single line to analyse may
covid_df[covid_df.month==5][['new_cases','new_deaths','new_tests']].sum()

new_cases       29073.0
new_deaths       5658.0
new_tests     1078720.0
dtype: float64

In [59]:
covid_df.new_cases.mean()  # overall avg

np.float64(1097.282258064516)

In [60]:
covid_df[covid_df.weekday==6].new_cases.mean()   # seems like more +ve cases found on sundays

np.float64(1247.2571428571428)

In [61]:
covid_df

          date  new_cases  new_deaths  new_tests  years  month  day  weekday
0   2019-12-31        0.0         0.0        NaN   2019     12   31        1
1   2020-01-01        0.0         0.0        NaN   2020      1    1        2
2   2020-01-02        0.0         0.0        NaN   2020      1    2        3
3   2020-01-03        0.0         0.0        NaN   2020      1    3        4
4   2020-01-04        0.0         0.0        NaN   2020      1    4        5
..         ...        ...         ...        ...    ...    ...  ...      ...
243 2020-08-30     1444.0         1.0    53541.0   2020      8   30        6
244 2020-08-31     1365.0         4.0    42583.0   2020      8   31        0
245 2020-09-01      996.0         6.0    54395.0   2020      9    1        1
246 2020-09-02      975.0         8.0        NaN   2020      9    2        2
247 2020-09-03     1326.0         6.0        NaN   2020      9    3        3

[248 rows x 8 columns]

In [62]:
# using groupby()
# so lets using the groupby , sumarise the data on monthly basis for better analysis
covid_month_df = covid_df.groupby('month')[['new_cases','new_deaths','new_tests']].sum()      #[['new_cases','new_deaths','new_tests']].sum()  to sum those on monthly basis
covid_month_df
# now we are getting a better view of our data
#similarly we can also check .mean() i.e avg of each month instead of .sum()

       new_cases  new_deaths  new_tests
month
1            3.0         0.0        0.0
2          885.0        21.0        0.0
3       100851.0     11570.0        0.0
4       101852.0     16091.0   419591.0
5        29073.0      5658.0  1078720.0
6         8383.0      1404.0   830354.0
7         6722.0       388.0   797692.0
8        21060.0       345.0  1098704.0
9         3297.0        20.0    54395.0
12           0.0         0.0        0.0

In [63]:
#now
covid_weekday_df = covid_df.groupby('weekday')[['new_cases','new_deaths','new_tests']].mean()      # avg of each day 0=monday , 6=sunday 
covid_weekday_df
# so can see the most cases are found at sunday and most tests cinducted at friday , so maybe the test results takes 2 days to come and thats why sunday has most +ve cases , maybe

           new_cases  new_deaths     new_tests
weekday
0        1109.142857  124.800000  19826.700000
1         918.638889  129.944444  31166.900000
2         927.305556  144.750000  34665.210526
3        1095.666667  141.472222  34488.578947
4        1189.714286  144.885714  39225.684211
5        1203.257143  157.000000  34589.473684
6        1247.257143  159.457143  28588.105263

In [64]:
covid_df['total_cases'] = covid_df.new_cases.cumsum()
covid_df['total_deaths'] = covid_df.new_deaths.cumsum()
covid_df['total_tests'] = covid_df.new_tests.cumsum() + initial_tests
covid_df
#cumsum genrally just adds value with each new case , and there are cummean(),cummax() etc...

,date,new_cases,new_deaths,new_tests,years,month,day,weekday,total_cases,total_deaths,total_tests
0,2019-12-31,0.0,0.0,NaN,2019,12,31,1,0.0,0.0,NaN
1,2020-01-01,0.0,0.0,NaN,2020,1,1,2,0.0,0.0,NaN
2,2020-01-02,0.0,0.0,NaN,2020,1,2,3,0.0,0.0,NaN
3,2020-01-03,0.0,0.0,NaN,2020,1,3,4,0.0,0.0,NaN
4,2020-01-04,0.0,0.0,NaN,2020,1,4,5,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
243,2020-08-30,1444.0,1.0,53541.0,2020,8,30,6,267464.0,35473.0,5117788.0
244,2020-08-31,1365.0,4.0,42583.0,2020,8,31,0,268829.0,35477.0,5160371.0
245,2020-09-01,996.0,6.0,54395.0,2020,9,1,1,269825.0,35483.0,5214766.0
246,2020-09-02,975.0,8.0,NaN,2020,9,2,2,270800.0,35491.0,NaN
247,2020-09-03,1326.0,6.0,NaN,2020,9,3,3,272126.0,35497.0,NaN

In [65]:
from urllib.request import urlretrieve
urlretrieve('https://raw.githubusercontent.com/aditya08xyz/practise-csv-file/refs/heads/main/locations.csv','location.csv')

('location.csv', <http.client.HTTPMessage at 0x298f907ed70>)

In [66]:
locations_df = pd.read_csv('location.csv')
locations_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,3.892834e+07,64.83,0.500,1803.987
1,Albania,Europe,2.877800e+06,78.57,2.890,11803.431
2,Algeria,Africa,4.385104e+07,76.88,1.900,13913.839
3,Andorra,Europe,7.726500e+04,83.73,NaN,NaN
4,Angola,Africa,3.286627e+07,61.15,NaN,5819.495
...,...,...,...,...,...,...
207,Yemen,Asia,2.982597e+07,66.12,0.700,1479.147
208,Zambia,Africa,1.838396e+07,63.89,2.000,3689.251
209,Zimbabwe,Africa,1.486293e+07,61.49,1.700,1899.775
210,World,NaN,7.794799e+09,72.58,2.705,15469.207
211,International,NaN,NaN,NaN,NaN,NaN

In [67]:
locations_df[locations_df.location== "Italy"]

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
97,Italy,Europe,60461828.0,83.51,3.18,35220.084

In [72]:
# now since our above covid data was over the italy 
covid_df['location'] = 'Italy'      # its capital i in italy
covid_df
# covid_df['location'] = locations_df[locations_df.location]  , if it was the data from different different loaction

,date,new_cases,new_deaths,new_tests,years,month,day,weekday,total_cases,total_deaths,total_tests,location
0,2019-12-31,0.0,0.0,NaN,2019,12,31,1,0.0,0.0,NaN,Italy
1,2020-01-01,0.0,0.0,NaN,2020,1,1,2,0.0,0.0,NaN,Italy
2,2020-01-02,0.0,0.0,NaN,2020,1,2,3,0.0,0.0,NaN,Italy
3,2020-01-03,0.0,0.0,NaN,2020,1,3,4,0.0,0.0,NaN,Italy
4,2020-01-04,0.0,0.0,NaN,2020,1,4,5,0.0,0.0,NaN,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...
243,2020-08-30,1444.0,1.0,53541.0,2020,8,30,6,267464.0,35473.0,5117788.0,Italy
244,2020-08-31,1365.0,4.0,42583.0,2020,8,31,0,268829.0,35477.0,5160371.0,Italy
245,2020-09-01,996.0,6.0,54395.0,2020,9,1,1,269825.0,35483.0,5214766.0,Italy
246,2020-09-02,975.0,8.0,NaN,2020,9,2,2,270800.0,35491.0,NaN,Italy
247,2020-09-03,1326.0,6.0,NaN,2020,9,3,3,272126.0,35497.0,NaN,Italy

In [73]:
# now to merge 
merge_df = covid_df.merge(locations_df, on ="location")   # on location , beacuse that was the common in both dataframe
merge_df

,date,new_cases,new_deaths,new_tests,years,month,day,weekday,total_cases,total_deaths,total_tests,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,2019-12-31,0.0,0.0,NaN,2019,12,31,1,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084
1,2020-01-01,0.0,0.0,NaN,2020,1,1,2,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084
2,2020-01-02,0.0,0.0,NaN,2020,1,2,3,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084
3,2020-01-03,0.0,0.0,NaN,2020,1,3,4,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084
4,2020-01-04,0.0,0.0,NaN,2020,1,4,5,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,2020-08-30,1444.0,1.0,53541.0,2020,8,30,6,267464.0,35473.0,5117788.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
244,2020-08-31,1365.0,4.0,42583.0,2020,8,31,0,268829.0,35477.0,5160371.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
245,2020-09-01,996.0,6.0,54395.0,2020,9,1,1,269825.0,35483.0,5214766.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
246,2020-09-02,975.0,8.0,NaN,2020,9,2,2,270800.0,35491.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084
247,2020-09-03,1326.0,6.0,NaN,2020,9,3,3,272126.0,35497.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084

In [75]:
merge_df['cases_per_million'] = merge_df.total_cases * 1e6 / merge_df.population
merge_df['deaths_per_million'] = merge_df.total_deaths * 1e6 / merge_df.population
merge_df['tests_per_million'] = merge_df.total_tests * 1e6 / merge_df.population

In [76]:
merge_df

,date,new_cases,new_deaths,new_tests,years,month,day,weekday,total_cases,total_deaths,total_tests,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,cases_per_million,deaths_per_million,tests_per_million
0,2019-12-31,0.0,0.0,NaN,2019,12,31,1,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,0.000000,0.000000,NaN
1,2020-01-01,0.0,0.0,NaN,2020,1,1,2,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,0.000000,0.000000,NaN
2,2020-01-02,0.0,0.0,NaN,2020,1,2,3,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,0.000000,0.000000,NaN
3,2020-01-03,0.0,0.0,NaN,2020,1,3,4,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,0.000000,0.000000,NaN
4,2020-01-04,0.0,0.0,NaN,2020,1,4,5,0.0,0.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,2020-08-30,1444.0,1.0,53541.0,2020,8,30,6,267464.0,35473.0,5117788.0,Italy,Europe,60461828.0,83.51,3.18,35220.084,4423.683650,586.700753,84644.943252
244,2020-08-31,1365.0,4.0,42583.0,2020,8,31,0,268829.0,35477.0,5160371.0,Italy,Europe,60461828.0,83.51,3.18,35220.084,4446.259878,586.766910,85349.238862
245,2020-09-01,996.0,6.0,54395.0,2020,9,1,1,269825.0,35483.0,5214766.0,Italy,Europe,60461828.0,83.51,3.18,35220.084,4462.733082,586.866146,86248.897403
246,2020-09-02,975.0,8.0,NaN,2020,9,2,2,270800.0,35491.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,4478.858959,586.998461,NaN
247,2020-09-03,1326.0,6.0,NaN,2020,9,3,3,272126.0,35497.0,NaN,Italy,Europe,60461828.0,83.51,3.18,35220.084,4500.790151,587.097697,NaN

In [ ]:
# ahhh we ve done alot of analysis , and tons of columns 20 and much of it we dont need , so lets clean up
result_df = merge_df[['new_cases','total_cases','new_deaths','total_deaths','new_tests','total_tests','cases_per_million','deaths_per_million','tests_per_million']]
result_df

,new_cases,total_cases,new_deaths,total_deaths,new_tests,total_tests,cases_per_million,deaths_per_million,tests_per_million
0,0.0,0.0,0.0,0.0,NaN,NaN,0.000000,0.000000,NaN
1,0.0,0.0,0.0,0.0,NaN,NaN,0.000000,0.000000,NaN
2,0.0,0.0,0.0,0.0,NaN,NaN,0.000000,0.000000,NaN
3,0.0,0.0,0.0,0.0,NaN,NaN,0.000000,0.000000,NaN
4,0.0,0.0,0.0,0.0,NaN,NaN,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...
243,1444.0,267464.0,1.0,35473.0,53541.0,5117788.0,4423.683650,586.700753,84644.943252
244,1365.0,268829.0,4.0,35477.0,42583.0,5160371.0,4446.259878,586.766910,85349.238862
245,996.0,269825.0,6.0,35483.0,54395.0,5214766.0,4462.733082,586.866146,86248.897403
246,975.0,270800.0,8.0,35491.0,NaN,NaN,4478.858959,586.998461,NaN
247,1326.0,272126.0,6.0,35497.0,NaN,NaN,4500.790151,587.097697,NaN

In [ ]:
# now to save the file will use .to_csv function
result_df.to_csv('results.csv' , index=None)           # index is none cuz i dont want it to make a cloumn of sno. i.e 1 to 247
# we made our analysis and put it in results.csv file can check in folder.

In [ ]:
# now we can plot some graphs with the help of pandas
result_df.new_cases.plot();          # result will not see cuz ive slected defult metplot for plotting but just for knowledge we can with pandas

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.